=== nicolashernandez/dev-star/uima-star/uima-mapper/src/main/resources/annotationMapperRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	elementFormDefault="qualified">
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->


	<!-- conceptSet : plusieurs rules pour créer les mêmes anntations
	
	-->
	
	<!-- context sur lequel on applique la règle avec les contraintes on veut que match aux bornes  
	
	-->
	<!--
		rule <xs:attribute name="priority" type="xs:decimal" use="optional" />
		<xs:attribute name="confidence" type="xs:decimal" use="optional" />
		<xs:attribute name="matchStrategy" use="required"> <xs:simpleType>
		<xs:restriction base="xs:string"> <xs:enumeration value="matchFirst"
		/> <xs:enumeration value="matchAll" /> <xs:enumeration
		value="matchComplete" /> </xs:restriction> </xs:simpleType>
		</xs:attribute> 
		
			-->
				<!--
			patternElement <xs:attribute name="positiveSet"
		type="xs:boolean" use="optional" /> <xs:attribute name="quantifier"
		type="xs:string" use="optional" />
					-->
				<!--
		 begin et end ont des default soit
		le patternElement soit les begin et end des patternElement des
		extrémités du pattern la création sur un seul patternElement, peut se
		dire de deux manières différentes ; group réfère au nieme patternElement
		start et end désigne le begin ou le end de celui-ci
			-->

	<xs:element name="rules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rule" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<!-- la séquence suivante est à supprimer -->
		</xs:complexType>
	</xs:element>

	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pattern" />
				<xs:element ref="create" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional" />
			<xs:attribute name="description" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="pattern">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="patternElement" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="patternElement">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="constraint" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="create" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="update" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="constraint">
		<xs:complexType mixed="true" />
	</xs:element>

	<xs:element name="create">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="begin" minOccurs="0" maxOccurs="1" />
				<xs:element ref="end" minOccurs="0" maxOccurs="1" />
				<xs:element ref="setFeature" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="update">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="setFeature" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="begin">
		<xs:complexType>
			<xs:attribute name="group" use="required" type="xs:integer" />
			<xs:attribute name="location" use="optional" default="start">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="start" />
						<xs:enumeration value="end" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="end">
		<xs:complexType>
			<xs:attribute name="group" use="required" type="xs:integer" />
			<xs:attribute name="location" use="optional" default="end">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="start" />
						<xs:enumeration value="end" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="setFeature">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nicolashernandez/dev-star/uima-star/uima-connectors/src/main/resources/mapper/rules/P7T2sw+mw+chunk-commonTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- * Licensed to the Apache Software Foundation (ASF) under one * or more 
	contributor license agreements. See the NOTICE file * distributed with this 
	work for additional information * regarding copyright ownership. The ASF 
	licenses this file * to you under the Apache License, Version 2.0 (the * 
	"License"); you may not use this file except in compliance * with the License. 
	You may obtain a copy of the License at * * http://www.apache.org/licenses/LICENSE-2.0 
	* * Unless required by applicable law or agreed to in writing, * software 
	distributed under the License is distributed on an * "AS IS" BASIS, WITHOUT 
	WARRANTIES OR CONDITIONS OF ANY * KIND, either express or implied. See the 
	License for the * specific language governing permissions and limitations 
	* under the License. -->
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xsi:schemaLocation="annotationMapperRules.xsd">


	<rule id="P7TSentence2CommonTypes" description="">
		<pattern>
			<patternElement type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName="SENT"]</constraint>
				<create type="common.types.text.Sentence">
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw2CommonTypes" description="">
		<pattern>
			<patternElement type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName="w" and (./*[@qualifiedName="sw" and
					@value="true"] or ./*[@qualifiedName="mw" and @value="true"])]
				</constraint>
				<create type="common.types.text.Token">
					<setFeature name="catP" value="./*[@qualifiedName='catP']/@value" />
					<setFeature constraint="./*[@qualifiedName='gender']/@value"
						name="gender" value="./*[@qualifiedName='gender']/@value" />
					<setFeature constraint="./*[@qualifiedName='number']/@value"
						name="number" value="./*[@qualifiedName='number']/@value" />
					<setFeature constraint="./*[@qualifiedName='mood']/@value"
						name="mood" value="./*[@qualifiedName='mood']/@value" />
					<setFeature constraint="./*[@qualifiedName='person']/@value"
						name="person" value="./*[@qualifiedName='person']/@value" />
					<setFeature constraint="./*[@qualifiedName='lemma']/@value"
						name="lemma" value="./*[@qualifiedName='lemma']/@value" />
					<setFeature constraint="./*[@qualifiedName='subcat']/@value"
						name="subCat" value="./*[@qualifiedName='subcat']/@value" />
					<setFeature constraint="./*[@qualifiedName='cat']/@value"
						name="cat" value="./*[@qualifiedName='cat']/@value" />
					<setFeature constraint="./*[@qualifiedName='mph']/@value"
						name="mph" value="./*[@qualifiedName='mph']/@value" />
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw-chunk-NP2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='NP' and (parent[@qualifiedName!='w'])]</constraint> 
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('NP')" />
					<setFeature constraint="./*[@qualifiedName='fct']/@value"
						name="fct" value="./*[@qualifiedName='fct']/@value" />
				</create>
			</patternElement>
		</pattern>
	</rule>
	<rule id="P7TWord-sw+mw-chunk-VN2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='VN' and (parent[@qualifiedName!='w'])]</constraint>
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('VN')" />
          <setFeature constraint="./*[@qualifiedName='fct']/@value"
            name="fct" value="./*[@qualifiedName='fct']/@value" />
					
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw-chunk-PP2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='PP' and (parent[@qualifiedName!='w'])]</constraint>
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('PP')" />
          <setFeature constraint="./*[@qualifiedName='fct']/@value"
            name="fct" value="./*[@qualifiedName='fct']/@value" />
					
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw-chunk-AP2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='AP' and (parent[@qualifiedName!='w'])]</constraint>
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('AP')" />
          <setFeature constraint="./*[@qualifiedName='fct']/@value"
            name="fct" value="./*[@qualifiedName='fct']/@value" />
					
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw-chunk-AdP2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='AdP' and (parent[@qualifiedName!='w'])]</constraint>
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('AdP')" />
          <setFeature constraint="./*[@qualifiedName='fct']/@value"
            name="fct" value="./*[@qualifiedName='fct']/@value" />
					
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw-chunk-VPinf2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='VPinf' and (parent[@qualifiedName!='w'])]</constraint>
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('VPinf')" />
          <setFeature constraint="./*[@qualifiedName='fct']/@value"
            name="fct" value="./*[@qualifiedName='fct']/@value" />
					
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw-chunk-VPpart2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='VPpart' and (parent[@qualifiedName!='w'])]</constraint>
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('VPpart')" />
          <setFeature constraint="./*[@qualifiedName='fct']/@value"
            name="fct" value="./*[@qualifiedName='fct']/@value" />
					
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw-chunk-Sint2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='Sint' and (parent[@qualifiedName!='w'])]</constraint>
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('Sint')" />
          <setFeature constraint="./*[@qualifiedName='fct']/@value"
            name="fct" value="./*[@qualifiedName='fct']/@value" />
					
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw-chunk-Srel2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='Srel' and (parent[@qualifiedName!='w'])]</constraint>
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('Srel')" />
          <setFeature constraint="./*[@qualifiedName='fct']/@value"
            name="fct" value="./*[@qualifiedName='fct']/@value" />
					
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw-chunk-Ssub2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='Ssub' and (parent[@qualifiedName!='w'])]</constraint>
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('Ssub')" />
          <setFeature constraint="./*[@qualifiedName='fct']/@value"
            name="fct" value="./*[@qualifiedName='fct']/@value" />
					
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="P7TWord-sw+mw-chunk-COORD2CommonTypes" description="">
		<pattern>
			<patternElement
				type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName='COORD' and (parent[@qualifiedName!='w'])]</constraint>
				<create type="common.types.text.Chunk">
					<setFeature name="chunkType" value="normalize-space('COORD')" />
          <setFeature constraint="./*[@qualifiedName='fct']/@value"
            name="fct" value="./*[@qualifiedName='fct']/@value" />
					
				</create>
			</patternElement>
		</pattern>
	</rule>
	<!-- More rule examples in Poulard Reported Speech to common types -->


</rules>

=== nicolashernandez/dev-star/uima-star/uima-opennlp/bin/src/main/resources/mapper/FrenchTreebankXML2CAS-to-UnivNantesLINATS.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xsi:schemaLocation="annotationMapperRules.xsd">
	
 	
	<rule id="XMLElementAnnotation2OpenNLPSentence" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='SENT']</constraint>
				<create type="common.types.text.Sentence" >
				
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	<!--
	In the orginal French Treebank format, how to select all the w element  which are word simple or part of compound but a compound  
	 -->
	<!-- 
	<rule id="XMLAttributeAnnotation2OpenNLPToken" 
		description="In the orginal French Treebank format, how to select all the w element  which are word simple or part of compound but a compound ">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLAttributeAnnotation">
				<constraint>.[(@elementName='w')  and ((@attributeName='cat') or (@attributeName='catint'))  and not(contains(@coveredText,' '))]</constraint>
				<create type="opennlp.uima.Token" >
						<setFeature name="pos" value="./@attributeValue"/>
				</create>
			</patternElement>
		</pattern>
	</rule>

	-->
	<!--  				<constraint>.[(@elementName='w') and  (contains(@attributesString,'cat="')) and (not(contains(@attributesString,',compound="')) or (contains(@attributesString,',compound="word"'))) and (not(contains(@attributesString,',raw=""'))) ]</constraint>
	 -->
	<rule id="XMLAttributeAnnotation2OpenNLPToken" 
		description="In the revised French Treebank format, how to select all the w element which are simple word or compound word but not a locution or a locution word ">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[(@elementName='w') and  (contains(@attributesString,'cat="')) and (not(contains(@attributesString,',compound="')) or (contains(@attributesString,',compound="word"'))) and (not(contains(@attributesString,',raw=""'))) ]</constraint>
				<create type="common.types.text.Token" >
						<setFeature name="raw" value="substring-after(substring-before(./@attributesString,'&#x0022;$'),'raw=&#x0022;')"/>
						<setFeature name="posTag" value="substring-after(substring-before(./@attributesString,'&#x0022;,ee='),'cat=&#x0022;')"/>
						<setFeature name="lemma" value="substring-after(substring-before(./@attributesString,'&#x0022;,mph='),'lemma=&#x0022;')"/>
						<setFeature name="mph" value="substring-after(substring-before(./@attributesString,'&#x0022;,subcat='),'mph=&#x0022;')"/>
					 	<setFeature name="subCat" value="substring-after(substring-before(./@attributesString,'&#x0022;,raw='),'subcat=&#x0022;')"/> 
						
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	<rule id="XMLAttributeAnnotation2OpenNLPToken" 
		description="In the revised French Treebank format, how to select all the w element which are a locution word">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[(@elementName='w') and (contains(@attributesString,'compoundPart="locution"')) and (not(contains(@attributesString,',raw=""')))]</constraint>
				<create type="common.types.text.Token" >
						<setFeature name="raw" value="substring-after(substring-before(./@attributesString,'&#x0022;$'),'raw=&#x0022;')"/>
						<setFeature name="posTag" value="substring-after(substring-before(./@attributesString,'&#x0022;,raw='),'catint=&#x0022;')"/>
						<setFeature name="lemma" value=" translate(substring-after(substring-before(./@attributesString, '&#x0022;$'),'raw=&#x0022;'), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')"/>
				 </create>
			</patternElement>
		</pattern>
	</rule>
	
	<rule id="NPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='NP']</constraint>
				<create type="common.types.Chunk" >
						<setFeature name="chunkType" value="normalize-space('NP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	
	<rule id="VPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='VN']</constraint>
				<create type="fr.univnantes.lina.uima.types.Chunk" >
						<setFeature name="chunkType" value="normalize-space('VP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	<rule id="PPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='PP']</constraint>
				<create type="fr.univnantes.lina.uima.types.Chunk" >
						<setFeature name="chunkType" value="normalize-space('PP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>
	
		<rule id="AdjPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='AP']</constraint>
				<create type="fr.univnantes.lina.uima.types.Chunk" >
						<setFeature name="chunkType" value="normalize-space('AdjP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>
	
  	<rule id="AdvPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='AdP']</constraint>
				<create type="fr.univnantes.lina.uima.types.Chunk" >
						<setFeature name="chunkType" value="normalize-space('AdvP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>


	
	  	<rule id="VPinfPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='VPinf']</constraint>
				<create type="fr.univnantes.lina.uima.types.Chunk" >
						<setFeature name="chunkType" value="normalize-space('VP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="VPpartPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='VPpart']</constraint>
				<create type="fr.univnantes.lina.uima.types.Chunk" >
						<setFeature name="chunkType" value="normalize-space('VP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>

</rules>

=== nicolashernandez/dev-star/uima-star/uima-opennlp/bin/target/classes/mapper/P7T2SentenceToken-sw+mw-CommonTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xsi:schemaLocation="annotationMapperRules.xsd">
	
 	
	<rule id="XMLElementAnnotation2OCommonSentence" 
		description="">
		<pattern>
			<patternElement type="FrenchTreebankXML2CAS-to-UnivNantesLINATS.xml">
				<constraint>.[@qualifiedName='SENT']</constraint>
				<create type="common.types.text.Sentence" >
				
				</create>
			</patternElement>
		</pattern>
	</rule>
	

	-->
	<!-- 
	on the taln13 revised extended version
	//w[@sw="true" or @po="true"]
		 -->
	<rule id="XMLAttributeAnnotation2OpenNLPToken" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.</constraint>
				<create type="common.types.text.Token" >
					
				</create>
			</patternElement>
		</pattern>
	</rule>
	

</rules>

=== nicolashernandez/dev-star/uima-star/uima-connectors/src/main/resources/mapper/rules/P7T2sw+pomw-commonTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xsi:schemaLocation="annotationMapperRules.xsd">


	<rule id="P7TSentence2CommonTypes" 
		description="">
		<pattern>
			<patternElement type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName="SENT"]</constraint>
				<create type="common.types.text.Sentence" >
				</create>
			</patternElement>
		</pattern>
	</rule>

  
   <rule id="P7TWord-sw+pomw2CommonTypes" 
    description="">
    <pattern>
      <patternElement type="common.types.extml.XMLElementAnnotation">
        <constraint>.[@qualifiedName="w" and (./*[@qualifiedName="sw" and @value="true"] or ./*[@qualifiedName="po" and @value="true"])]</constraint>
        <create type="common.types.text.Token" >
             <setFeature name="subCat" value="./*[qualifiedName='catP']/@value"/>
     <!-- <setFeature name="cat" value="./*[qualifiedName='cat']/@value"/>
          <setFeature name="lemma" value="./*[qualifiedName='lemma']/@value"/>
          <setFeature name="gender" value="./*[qualifiedName='gender']/@value"/> 
          <setFeature name="number" value="./*[qualifiedName='number']/@value"/>
          <setFeature name="person" value="./*[qualifiedName='person']/@value"/> 
          <setFeature name="tense" value="./*[qualifiedName='tense']/@value"/>
          <setFeature name="mood" value="./*[qualifiedName='mood']/@value"/>
          <setFeature name="case" value="./*[qualifiedName='case']/@value"/> -->
        </create>
      </patternElement>
    </pattern>
  </rule>
	
	<!-- More rule examples in Poulard Reported Speech to common types -->
	

</rules>
