=== nicolashernandez/dev-star/uima-star/uima-mapper/src/main/resources/annotationMapperRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	elementFormDefault="qualified">
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->


	<!-- conceptSet : plusieurs rules pour créer les mêmes anntations
	
	-->
	
	<!-- context sur lequel on applique la règle avec les contraintes on veut que match aux bornes  
	
	-->
	<!--
		rule <xs:attribute name="priority" type="xs:decimal" use="optional" />
		<xs:attribute name="confidence" type="xs:decimal" use="optional" />
		<xs:attribute name="matchStrategy" use="required"> <xs:simpleType>
		<xs:restriction base="xs:string"> <xs:enumeration value="matchFirst"
		/> <xs:enumeration value="matchAll" /> <xs:enumeration
		value="matchComplete" /> </xs:restriction> </xs:simpleType>
		</xs:attribute> 
		
			-->
				<!--
			patternElement <xs:attribute name="positiveSet"
		type="xs:boolean" use="optional" /> <xs:attribute name="quantifier"
		type="xs:string" use="optional" />
					-->
				<!--
		 begin et end ont des default soit
		le patternElement soit les begin et end des patternElement des
		extrémités du pattern la création sur un seul patternElement, peut se
		dire de deux manières différentes ; group réfère au nieme patternElement
		start et end désigne le begin ou le end de celui-ci
			-->

	<xs:element name="rules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rule" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<!-- la séquence suivante est à supprimer -->
		</xs:complexType>
	</xs:element>

	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pattern" />
				<xs:element ref="create" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional" />
			<xs:attribute name="description" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="pattern">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="patternElement" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="patternElement">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="constraint" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="create" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="update" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="constraint">
		<xs:complexType mixed="true" />
	</xs:element>

	<xs:element name="create">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="begin" minOccurs="0" maxOccurs="1" />
				<xs:element ref="end" minOccurs="0" maxOccurs="1" />
				<xs:element ref="setFeature" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="update">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="setFeature" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="begin">
		<xs:complexType>
			<xs:attribute name="group" use="required" type="xs:integer" />
			<xs:attribute name="location" use="optional" default="start">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="start" />
						<xs:enumeration value="end" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="end">
		<xs:complexType>
			<xs:attribute name="group" use="required" type="xs:integer" />
			<xs:attribute name="location" use="optional" default="end">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="start" />
						<xs:enumeration value="end" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="setFeature">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nicolashernandez/dev-star/uima-star/uima-connectors/src/main/resources/mapper/rules/MUCXMLCAS2commonTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Licensed to the Apache Software Foundation (ASF) under one * or more 
	contributor license agreements. See the NOTICE file * distributed with this 
	work for additional information * regarding copyright ownership. The ASF 
	licenses this file * to you under the Apache License, Version 2.0 (the * 
	"License"); you may not use this file except in compliance * with the License. 
	You may obtain a copy of the License at * * http://www.apache.org/licenses/LICENSE-2.0 
	* * Unless required by applicable law or agreed to in writing, * software 
	distributed under the License is distributed on an * "AS IS" BASIS, WITHOUT 
	WARRANTIES OR CONDITIONS OF ANY * KIND, either express or implied. See the 
	License for the * specific language governing permissions and limitations 
	* under the License. -->
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xsi:schemaLocation="annotationMapperRules.xsd">

	<!-- Exemples extrait de Stern et Sagot -->
	<!-- <ENAMEX eid="2000000003014856" type="Location" sub_type="City" gnfeature="PPL" 
		gnccode="FR" name="Grasse">Grasse</ENAMEX> -->
	<!-- <EX_ENAMEX type="Organization" name="collège de Cannes">collège de 
		Cannes</EX_ENAMEX> -->
	<!-- <ENAMEX eid="1000000001207572" type="Person" name="Agustín Carstens">Agustin 
		Carstens</ENAMEX> -->

	<rule id="ENAMEXAny2CommonTypes" description="">
		<pattern>
			<patternElement
				type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="ENAMEX" and ./*[@qualifiedName='name']/@value]</constraint>
				<create type="common.types.ne.NamedEntity">
					<setFeature name="category" value="./*[@qualifiedName='type']/@value" />
					<setFeature name="value" value="./*[@qualifiedName='name']/@value" />
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="ENAMEXPerson2CommonTypes" description="">
		<pattern>
			<patternElement
				type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="ENAMEX" and ./*[@value="Person"] and ./*[@qualifiedName='name']/@value]
				</constraint>
				<create type="common.types.ne.Person">
					<setFeature name="value" value="./*[@qualifiedName='name']/@value" />
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="ENAMEXLocation2CommonTypes" description="">
		<pattern>
			<patternElement
				type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="ENAMEX" and ./*[@value="Location"] and ./*[@qualifiedName='name']/@value]
				</constraint>
				<create type="common.types.ne.Location">
					<setFeature name="value" value="./*[@qualifiedName='name']/@value" />
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="ENAMEXOrganization2CommonTypes" description="">
		<pattern>
			<patternElement
				type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="ENAMEX" and
					./*[@value="Organization"] and ./*[@qualifiedName='name']/@value]
				</constraint>
				<create type="common.types.ne.Organization">
					<setFeature name="value" value="./*[@qualifiedName='name']/@value" />
				</create>
			</patternElement>
		</pattern>
	</rule>

	<!-- Alternative create Person/Location/Organization from XMLattribute (faster 
		but from the XMLelement accept more constraints) -->
	<!-- <rule id="NESternCorpusENAMEXPerson2CommonTypes" description=""> <pattern> 
		<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLAttributeAnnotation"> 
		<constraint>.[@qualifiedName="type" and @value="Person" and ./element[@qualifiedName="ENAMEX"]] 
		</constraint> <create type="common.types.ne.Person"> </create> </patternElement> 
		</pattern> </rule> <rule id="NESternCorpusENAMEXLocation2CommonTypes" description=""> 
		<pattern> <patternElement type="fr.univnantes.lina.uima.connectors.types.XMLAttributeAnnotation"> 
		<constraint>.[@qualifiedName="type" and @value="Location" and ./element[@qualifiedName="ENAMEX"]] 
		</constraint> <create type="common.types.ne.Location"> </create> </patternElement> 
		</pattern> </rule> <rule id="NESternCorpusENAMEXOrganization2CommonTypes" 
		description=""> <pattern> <patternElement type="fr.univnantes.lina.uima.connectors.types.XMLAttributeAnnotation"> 
		<constraint>.[@qualifiedName="type" and @value="Organization" and ./element[@qualifiedName="ENAMEX"]] 
		</constraint> <create type="common.types.ne.Organization"> </create> </patternElement> 
		</pattern> </rule> -->

	<!-- Exemples extraits de A. Bittar FR-TimeBank -->
	<!-- <TIMEX3 anchorTimeID="t1" temporalFunction="true" tid="t6" type="DATE" 
		value="1999-05-23TEV" valueFromFunction="tf3">Dimanche soir</TIMEX3> -->
	<!-- <TIMEX3 endPoint="t1" temporalFunction="true" tid="t3" type="DURATION" 
		value="PXD" valueFromFunction="tf19">Ces derniers jours</TIMEX3> -->
	<!-- <TIMEX3 tid="t4" type="TIME" value="T14:00">14 h</TIMEX3> -->


	<rule id="TIMEX3Any2CommonTypes" description="">
		<pattern>
			<patternElement
				type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="TIMEX3" and
					not(./*[@qualifiedName="functionInDocument"])]
				</constraint>
				<create type="common.types.ne.NamedEntity">
					<setFeature name="category" value="./*[@qualifiedName='type']/@value" />
					<setFeature name="value" value="./*[@qualifiedName='value']/@value" />

				</create>
			</patternElement>
		</pattern>
	</rule>


	<rule id="TIMEX3Date2CommonTypes" description="">
		<pattern>
			<patternElement
				type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="TIMEX3"
					and
					not(./*[@qualifiedName="functionInDocument"])
					and
					./*[@value="DATE"]]
				</constraint>
				<create type="common.types.ne.Date">
					<setFeature name="value" value="./*[@qualifiedName='value']/@value" />
				</create>
			</patternElement>
		</pattern>
	</rule>


	<rule id="TIMEX3Time2CommonTypes" description="">
		<pattern>
			<patternElement
				type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="TIMEX3"
					and
					not(./*[@qualifiedName="functionInDocument"])
					and
					./*[@value="TIME"]]
				</constraint>
				<create type="common.types.ne.Time">
					<setFeature name="value" value="./*[@qualifiedName='value']/@value" />
				</create>
			</patternElement>
		</pattern>
	</rule>

	<!-- We should differ from date and time duration ; not the case actually -->
	<rule id="TIMEX3Duration2CommonTypes" description="">
		<pattern>
			<patternElement
				type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="TIMEX3"
					and not(./*[@qualifiedName="functionInDocument"])
					and
					./*[@value="DURATION"]]
				</constraint>
				<create type="common.types.ne.Duration">
					<setFeature name="value" value="./*[@qualifiedName='value']/@value" />
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	
  <!-- We should differ from date and time duration ; not the case actually -->
  <rule id="TIMEX3Set2CommonTypes" description="">
    <pattern>
      <patternElement
        type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
        <constraint>.[@qualifiedName="TIMEX3"
          and not(./*[@qualifiedName="functionInDocument"])
          and
          ./*[@value="SET"]]
        </constraint>
        <create type="common.types.ne.TimexSet">
          <setFeature name="value" value="./*[@qualifiedName='value']/@value" />
        </create>
      </patternElement>
    </pattern>
  </rule>

	<!-- More rule examples in Poulard Reported Speech to common types -->
</rules>

=== nicolashernandez/dev-star/uima-star/uima-opennlp/bin/src/main/resources/mapper/FrenchTreebankXML2CAS-to-ApacheUIMAAnnotation.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xsi:schemaLocation="annotationMapperRules.xsd">
	
	<!-- Fonctions XPath http://www.gchagnon.fr/cours/xml/fonctionsxpath.html#caracteres -->
	
  	<rule id="Sentence" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='SENT']</constraint>
				<create type="org.apache.uima.SentenceAnnotation" >
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	
	
	<!--
		<rule id="XMLAttributeAnnotationW2TokenAnnotationPosTag" 
		description="SÃ©lection de certaines valeurs d'attribut cat (pos), subcat (grammatical function e.g. suj...), mph (morphology e.g. 3ms, fp), ee (cat-subcat-mph), lemma (lemma)">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLAttributeAnnotation">
				<constraint>.[@elementName='w' and @attributeName='cat' and @attributeValue!=""]</constraint>
				<create type="org.apache.uima.TokenAnnotation" >
					<setFeature name="posTag" value="./@attributeValue"/>
				</create>
			</patternElement>
		</pattern>
	</rule> 
	 -->
	 <!--  and not(contains(@coveredText,' ')) -->
	
	
		<rule id="TokenAnnotation:pos" 
		description="training for posTagger">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLAttributeAnnotation">
				<constraint>.[@elementName='w' and @attributeName='cat']</constraint>
				<create type="org.apache.uima.TokenAnnotation" >
						<setFeature name="posTag" value="./@attributeValue"/>
				</create>
			</patternElement>
		</pattern>
	</rule>

</rules>
