=== nicolashernandez/dev-star/uima-star/uima-mapper/src/main/resources/annotationMapperRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	elementFormDefault="qualified">
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->


	<!-- conceptSet : plusieurs rules pour créer les mêmes anntations
	
	-->
	
	<!-- context sur lequel on applique la règle avec les contraintes on veut que match aux bornes  
	
	-->
	<!--
		rule <xs:attribute name="priority" type="xs:decimal" use="optional" />
		<xs:attribute name="confidence" type="xs:decimal" use="optional" />
		<xs:attribute name="matchStrategy" use="required"> <xs:simpleType>
		<xs:restriction base="xs:string"> <xs:enumeration value="matchFirst"
		/> <xs:enumeration value="matchAll" /> <xs:enumeration
		value="matchComplete" /> </xs:restriction> </xs:simpleType>
		</xs:attribute> 
		
			-->
				<!--
			patternElement <xs:attribute name="positiveSet"
		type="xs:boolean" use="optional" /> <xs:attribute name="quantifier"
		type="xs:string" use="optional" />
					-->
				<!--
		 begin et end ont des default soit
		le patternElement soit les begin et end des patternElement des
		extrémités du pattern la création sur un seul patternElement, peut se
		dire de deux manières différentes ; group réfère au nieme patternElement
		start et end désigne le begin ou le end de celui-ci
			-->

	<xs:element name="rules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rule" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<!-- la séquence suivante est à supprimer -->
		</xs:complexType>
	</xs:element>

	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pattern" />
				<xs:element ref="create" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional" />
			<xs:attribute name="description" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="pattern">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="patternElement" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="patternElement">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="constraint" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="create" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="update" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="constraint">
		<xs:complexType mixed="true" />
	</xs:element>

	<xs:element name="create">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="begin" minOccurs="0" maxOccurs="1" />
				<xs:element ref="end" minOccurs="0" maxOccurs="1" />
				<xs:element ref="setFeature" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="update">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="setFeature" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="begin">
		<xs:complexType>
			<xs:attribute name="group" use="required" type="xs:integer" />
			<xs:attribute name="location" use="optional" default="start">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="start" />
						<xs:enumeration value="end" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="end">
		<xs:complexType>
			<xs:attribute name="group" use="required" type="xs:integer" />
			<xs:attribute name="location" use="optional" default="end">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="start" />
						<xs:enumeration value="end" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="setFeature">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nicolashernandez/dev-star/uima-star/uima-connectors/src/main/resources/mapper/rules/SternNamedEntityCorpus2commonTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xsi:schemaLocation="annotationMapperRules.xsd">

	<rule id="NESternCorpusNewsItem2CommonTypes" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="news_item"]</constraint>
				<create type="common.types.text.Article" >
				</create>
			</patternElement>
		</pattern>
	</rule>
		
	<rule id="NESternCorpusNewsHeader2CommonTypes" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="news_head"]</constraint>
				<create type="common.types.text.Header" >
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	<rule id="NESternCorpusNewsTextCommonTypes" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="news_text"]</constraint>
				<create type="common.types.text.Text" >
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="NESternCorpusPara2CommonTypes" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="para"]</constraint>
				<create type="common.types.text.Paragraph" >
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	  <rule id="NESternCorpusENAMEX2CommonTypes" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="ENAMEX"]</constraint>
				<create type="common.types.classification.PositiveGoldSample" >
				</create>
			</patternElement>
		</pattern>
	</rule>
	<!--
		<rule id="NESternCorpusENAMEXLocation2CommonTypes" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLAttributeAnnotation">
				<constraint>.[@localName="type" and @value="Location"]</constraint>
				<create type="common.types.classification.PositiveGoldSample" >
				</create>
			</patternElement>
		</pattern>
	</rule>-->
	
	<!-- More rule examples in Poulard Reported Speech to common types -->
	
</rules>

=== nicolashernandez/dev-star/uima-star/uima-connectors/src/main/resources/mapper/rules/TutinArcadeCorpus2commonTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xsi:schemaLocation="annotationMapperRules.xsd">


	<rule id="TutinArcadeCorpusText2CommonTypes" 
		description="">
		<pattern>
			<patternElement type="common.types.extml.XMLElementAnnotation">
				<constraint>.[@qualifiedName="text"]</constraint>
				<create type="common.types.text.Text" >
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	 <rule id="TutinArcadeCorpusHead2CommonTypes" 
    description="">
    <pattern>
      <patternElement type="common.types.extml.XMLElementAnnotation">
        <constraint>.[@qualifiedName="head"]</constraint>
        <create type="common.types.text.Title" >
        </create>
      </patternElement>
    </pattern>
  </rule>
	
	  <rule id="TutinArcadeCorpusParagraph2CommonTypes" 
    description="">
    <pattern>
      <patternElement type="common.types.extml.XMLElementAnnotation">
        <constraint>.[@qualifiedName="p"]</constraint>
        <create type="common.types.text.Paragraph" >
        </create>
      </patternElement>
    </pattern>
  </rule>
  
  <!-- !! ne pas faire double emploi avec l'utilisation de la chaîne de traitement opennlp qui détecte aussi les phrases  -->
  <rule id="TutinArcadeCorpusSentence2CommonTypes" 
    description="">
    <pattern>
      <patternElement type="common.types.extml.XMLElementAnnotation">
        <constraint>.[@qualifiedName="s"]</constraint>
        <create type="common.types.text.Sentence" >
        </create>
      </patternElement>
    </pattern>
  </rule>
  
     <rule id="TutinArcadeCorpusCoreference2CommonTypes" 
    description="">
    <pattern>
      <patternElement type="common.types.extml.XMLElementAnnotation">
        <constraint>.[@qualifiedName="exp"]</constraint>
        <create type="common.types.coref.Coreference" >
          <setFeature name="id" value="./*[qualifiedName='id']/@value"/>
          <setFeature name="corefType" value="./*[qualifiedName='type']/@value"/>
          <setFeature name="src" value="./*[qualifiedName='src']/@value"/>
        
        </create>
      </patternElement>
    </pattern>
  </rule>
	
	<!-- More rule examples in Poulard Reported Speech to common types -->
	

</rules>

=== nicolashernandez/dev-star/uima-star/uima-connectors/src/main/resources/mapper/rules/PoulardReportedSpeechCorpus2commonTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xsi:schemaLocation="annotationMapperRules.xsd">
	
<rule id="corpus2ReportedSpeechDiscourse" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="cite:discours"]</constraint>
				<create type="common.types.rs.ReportedSpeechDiscourse" >
				</create>
			</patternElement>
		</pattern>
	</rule>

<rule id="corpus2ReportedSpeechSource" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="cite:source"]</constraint>
				<create type="common.types.rs.ReportedSpeechSource" >
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	
	<rule id="corpus2Article" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="corpus:article"]</constraint>
				<create type="common.types.text.Article" >
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	<rule id="corpus2Title" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="corpus:title"]</constraint>
				<create type="common.types.text.Title" >
				</create>
			</patternElement>
		</pattern>
	</rule>
	
		<rule id="corpus2Subtitle" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="corpus:subtitle"]</constraint>
				<create type="common.types.text.Subtitle" >
				</create>
			</patternElement>
		</pattern>
	</rule>
	
			<rule id="corpus2Header" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="corpus:header"]</constraint>
				<create type="common.types.text.Header" >
				</create>
			</patternElement>
		</pattern>
	</rule>

			<rule id="corpus2Paragraph" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@qualifiedName="corpus:paragraph"]</constraint>
				<create type="common.types.text.Paragraph" >
				</create>
			</patternElement>
		</pattern>
	</rule>
	
<!-- 	<rule id="Word2Mot,Nom" 
		description="contrainte sur attribut de type simple encapsulé dans un type complexe et creation de deux types">
		<pattern>
			<patternElement type="example.types.source.Word">
				<constraint>.[posType[value='nn']]</constraint>
				<create type="example.types.target.Mot" />
				<create type="example.types.target.Nom" />
			</patternElement>
		</pattern>
	</rule> -->
	
						<!-- <setFeature name="pos" value=".[posType[value]]"/> -->
	<!--  
	<rule id="Word2Adjectif" 
		description="setFeature">
		<pattern>
			<patternElement type="example.types.source.Word">
				<constraint>.[posType[value='jj']]</constraint>
				<create type="example.types.target.Adjectif" >
					<setFeature name="pos" value="./posType/@value"/>
				</create>
			</patternElement>
		</pattern>
	</rule>-->

	<!--  	<rule  id="PhraseSansVerbe" description="opérateurs booleens">
		<pattern>
			<patternElement type="example.types.source.Sentence">
				<constraint>.[
					not(
					wordArray[posType[contains(@value,'vb')]]
					or
					wordArray[posType[contains(@value,'be')]])
					]</constraint>
				<create type="example.types.target.PhraseSansVerbe" />
			</patternElement>
		</pattern>
	</rule>-->

	<!--  	<rule id="PhraseDiscoursRapporte"
		description="contrainte sur des attributs de type simple encapsulés dans un tableau de type complexe et creation d'un type">
		<pattern>
			<patternElement type="example.types.source.Sentence">
				<constraint>.[
					wordArray[
					posType[value='(']]/
					following-sibling::wordArray[
					@coveredText='said']/
					following-sibling::wordArray[
					posType[contains(@value,'np')]]]
				</constraint>
				<create type="example.types.target.PhraseDiscoursRapporte" />
			</patternElement>
		</pattern>
	</rule>-->

	<!--  	<rule id="NOMdeNOM">
		<pattern>
			<patternElement type="example.types.source.Word">
				<constraint>.[posType[value='nn'] and matches(@coveredText,'^[A-Z]')]
				</constraint>
			</patternElement>
			<patternElement type="example.types.source.Word">
				<constraint>.[@coveredText='de']</constraint>
			</patternElement>
			<patternElement type="example.types.source.Word">
				<constraint>.[posType[value='nn'] and matches(@coveredText,'^[A-Z]')]
				</constraint>
			</patternElement>

		</pattern>
		<create type="example.type.NounPhrase">
			<begin group="0" />
			<end group="0" />
		</create>
	</rule>
	 -->
	<!-- 
	<rule id="XMLAttributeAnnotationW2TokenAnnotationPosTag" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLAttributeAnnotation">
				<constraint>.[qualifiedName='w' and attributeName='cat']</constraint>
				<create type="org.apache.uima.TokenAnnotation" >
					<setFeature name="posTag" value=""/>
					<setFeature name="" value=""/>
				</create>
			</patternElement>
		</pattern>
	</rule>
 -->
 
	<!--
		Différents tests de sources FAIL java.lang.ClassNotFoundException:
		uima.tcas.Annotation FAIL
		org.apache.uima.analysis_engine.AnalysisEngineProcessException:
		EXCEPTION MESSAGE LOCALIZATION FAILED:
		java.util.MissingResourceException: Can't find resource for bundle
		java.util.PropertyResourceBundle, key Debug: Le type
		org.apache.uima.jcas.tcas.Annotation n'est pas déclaré dans le
		TypeSystem ! at
		fr.univnantes.lina.uima.TypeMapperAE.process(TypeMapperAE.java:90)
		FAIL java.lang.ClassNotFoundException: example.types.target.Annotation
	-->
	<!-- //*[posString='np'] lourd-->
	<!--
		<Rule name="" description="" priority="">
		<Source>example.types.source.Sentence</Source>
		<Constraint>//*[posString='np']</Constraint>
		<Target>example.types.target.Test</Target> </Rule>
	-->


	<!--


		<rule description=""> <pattern> <patternElement type="">
		<constraint></constraint> <create type=""/> </patternElement>
		</pattern> </rule> <rule id="" description=""> <pattern>
		<patternElement type=""> <constraint></constraint> <create type="">
		</create> <create type=""> <setFeature name="" value="" /> </create>
		<update type=""> <setFeature name="" value="" /> </update>
		</patternElement> <create type="" > <begin group="" location="" />
		<end group="" location="" /> <setFeature name="" value="" /> </create>
		</pattern> </rule>
	-->

</rules>

=== nicolashernandez/dev-star/uima-star/uima-opennlp/bin/target/classes/mapper/FrenchTreebankXML2CAS-to-OpenNLP.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		* Licensed to the Apache Software Foundation (ASF) under one * or more
		contributor license agreements. See the NOTICE file * distributed with
		this work for additional information * regarding copyright ownership.
		The ASF licenses this file * to you under the Apache License, Version
		2.0 (the * "License"); you may not use this file except in compliance
		* with the License. You may obtain a copy of the License at * *
		http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
		applicable law or agreed to in writing, * software distributed under
		the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
		OR CONDITIONS OF ANY * KIND, either express or implied. See the
		License for the * specific language governing permissions and
		limitations * under the License.
	-->
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.lina.univ-nantes.fr/uima/annotationmapper"
	xsi:schemaLocation="annotationMapperRules.xsd">
	
 	
	<rule id="XMLElementAnnotation2OpenNLPSentence" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='SENT']</constraint>
				<create type="opennlp.uima.Sentence" >
				
				</create>
			</patternElement>
		</pattern>
	</rule>
	

	
	<rule id="XMLAttributeAnnotation2OpenNLPToken" 
		description="In the orginal French Treebank format, how to select all the w element  which are word simple or part of compound but a compound ">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLAttributeAnnotation">
				<constraint>.[(@elementName='w')  and ((@attributeName='cat') or (@attributeName='catint'))  and not(contains(@coveredText,' '))]</constraint>
				<create type="opennlp.uima.Token" >
						<setFeature name="pos" value="./@attributeValue"/>
				</create>
			</patternElement>
		</pattern>
	</rule>

	
	
	<rule id="NPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='NP']</constraint>
				<create type="opennlp.uima.Chunk" >
						<setFeature name="chunkType" value="normalize-space('NP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	
	<rule id="VPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='VN']</constraint>
				<create type="opennlp.uima.Chunk" >
						<setFeature name="chunkType" value="normalize-space('VP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	<rule id="PPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='PP']</constraint>
				<create type="opennlp.uima.Chunk" >
						<setFeature name="chunkType" value="normalize-space('PP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>
	
		<rule id="AdjPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='AP']</constraint>
				<create type="opennlp.uima.Chunk" >
						<setFeature name="chunkType" value="normalize-space('AdjP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>
	
  	<rule id="AdvPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='AdP']</constraint>
				<create type="opennlp.uima.Chunk" >
						<setFeature name="chunkType" value="normalize-space('AdvP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>

  	<rule id="AdvPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='AdP']</constraint>
				<create type="opennlp.uima.Chunk" >
						<setFeature name="chunkType" value="normalize-space('AdvP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>
	
	  	<rule id="VPinfPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='VPinf']</constraint>
				<create type="opennlp.uima.Chunk" >
						<setFeature name="chunkType" value="normalize-space('VP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>

	<rule id="VPpartPChunk" 
		description="">
		<pattern>
			<patternElement type="fr.univnantes.lina.uima.connectors.types.XMLElementAnnotation">
				<constraint>.[@elementName='VPpart']</constraint>
				<create type="opennlp.uima.Chunk" >
						<setFeature name="chunkType" value="normalize-space('VP')"/>
				</create>
			</patternElement>
		</pattern>
	</rule>

</rules>
